// suppress inspection "SpellCheckingInspection" for whole file
:toc:
:toclevels: 4

= `thincrest-pcond`: Test Assertion Library

`thincrest-pcond` is a test assertion library named after `hamcrest`<<hamcrest>> and it is at the same time a pun for "think the rest".
It uses `pcond`, instead of `Matcher` used by `hamcrest`, for a mechanism to compose human-readable messages.
The benefit of `pcond` over `hamcrest` is its compatibility and extensibility because they are not relying on custom classes like `Matcher` but on Java's plain `Predicate`.
It is why it is "thinner" than `hamcrest`.
It also provides useful preset predicates from which you can build your own for more complex types and checks.
So, you can reuse the predicates you created across different use cases such as value-checking<<GuavaPreconditions>>, DbC contracts<<DbC>>, or test assertions.

For full documentation, visit https://dakusui.github.io/thincrest/[here].
Also, check its https://dakusui.github.io/thincrest/thincrest-pcond.html[overview].

== Getting Started

Have a following maven dependency in your `pom.xml`.

[source,xml]
[subs="verbatim,attributes"]
----
<dependency>
  <groupId>com.github.dakusui</groupId>
  <artifactId>thincrest-pcond</artifactId>
  <version>{thincrest-pcond-version}</version>
</dependency>
----

Visit https://oss.sonatype.org/[oss.sonatype.org] to figure out the most recent version of `thincrest-pcond`.


== Building the `thincrest-pcond` Library

=== How to Build the Project

Compile and Test:: `mvn clean compile test`
Docs:: `mvn clean compile test site`, you will see generated docs under `target/site` directory.

=== Build dependencies

- Java SDK8 (`openjdk-8-jdk`)
- `mvn` (`maven`)
- `gem` (`ruby`)
- `xmllint` (`libxml2-utils`)
- `git` (`git`)

[bibliography]
== References

- [[[DbC, 1]]] Wikipedia article on Design by Contract, https://en.wikipedia.org/wiki/Design_by_contract
- [[[v4j, 2]]] Valid4j, http://www.valid4j.org
- [[[GuavaPreconditions, 3]]] PreconditionsExplained, https://github.com/google/guava/wiki/PreconditionsExplained
- [[[hamcrest, 4]]] Hamcrest https://hamcrest.org/
