= `thincrest`: The Best Test Assertion Library Ever

`thincrest` is a test assertion library, which aims at overcoming drawbacks in existing ones, such as Hamcrest, AssertJ, or Google Truth.
It also equips a feature for "Metamorphic testing".

== Design Goals

Following is a list of goals that the `pcond` library tries to achieve.

* **More Programmer-Friendly Readability and Writability:** Test assertion libraries have more and more focused on writability of code from readability of code and output.
The `pcond` makes one step further by addressing remaining pain points.
** **Remove repeating the same fact twice in the failure message and the predicate:** More or less similar to Google Guava's `Preconditions` class, a human needs to describe the condition to be checked twice.
One is in a natural language to print what condition is violated.
And the other is in Java programming language to define what check should be done for a given value.
This is a practice that violates "D-R-Y" (Don't repeat yourself) principle.
This is more important for programmers than printing a nice message on a failure.
** **Remove fail->fix->run loop:** In the earliest age of JUnit, there used not to be a good way to verify multiple conditions in one test method.
Programmers needed to call `assert`, `assertEquals`, etc. multiple times from inside one test method.
This was causing a situation, where they need to repeat fail->fix->run->fail->fix->run... loop, once an assert method call fails.
Ensuring a good way to write a test method with only a single assertion method call is important.
** **Easy to handle custom types:** Test assertion libraries require users to implement custom value verifier (`Matcher` in Hamcrest, `Assert` in AssertJ, `Subject` in Google Truth) classes.
This is a significant work by itself, and it may also impede refactorings of the software under test.
** **Human-analyzable output:** A readable message is essential to understand what happened when a check fails.
However, the `pcond` interprets it in a slightly different way from other existing assertion libraries.
It focuses more on making a failure report self-sufficient and structured.
Rather than making it look "natural" as if it were written by a human, it focuses on make it readable for *programmers*.
Not for general English-speaking human.
* **Make custom verifiers composable:** Instead of let a user define a custom verifier for every type, `pcond` offers a way to compose a verifier for a user type from already provided functions and predicates.

== Design

`thincrest` employs `pcond` for composing human-readable error messages.



== Entry points

The package link:com/github/dakusui/thincrest/package-summary.html:[`com.github.dakusui.pcond`] holds entry point classes of the `pcond` library.

It supports two styles.
One is traditional "Hamcrest" like style and the other is more recently fashioned "fluent" style like AssertJ or Google Truth.

=== Hamcrest Style

Hamcrest [<<hamcrest>>] is the first popular assertion library.
The style JUnit itself presented at the time Hamcrest was published is to call `assertEquals`, `assertTrue`, `assertFalse` methods.
Those methods fail if the given value do not satisfy the desired condition.
Also, they print human-readable message about what happened. That is, what the given value was and what was expected.

This approach leads to an explosion of the number of `assertXyz` methods because we need to verify values with a lot of different expectations and, for each of them, this approach requires one `assertXyz` method.

Hamcrest separated an assertion into two parts, one of which controls a value checking flow and the other is the part that defines a condition to be satisfied.

Following is an example found in Hamcrest's tutorial[<<hamcrest-tutorial>>]:

[source, java]
----
import org.junit.jupiter.api.Test;
import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.*;

public class BiscuitTest {
  @Test
  public void testEquals() {
    Biscuit theBiscuit = new Biscuit("Ginger");
    Biscuit myBiscuit = new Biscuit("Ginger");
    assertThat(theBiscuit, equalTo(myBiscuit)); // The Line
  }
}
----

The object returned by a static method `Matchers.equalTo` is a `Matcher` object as other static methods in the class do.
The example verifies if `theBuiscuit` is `equalTo` `myBiscuit` as it says.

Suppose if `myBiscuit` is `Sugar` and this test fails, the following message will be printed:

----
java.lang.AssertionError:
Expected: <Sugar>
     but: was <Ginger>
Expected :<Sugar>
Actual   :<Ginger>
----

If we want to test a different expectation, for instance, suppose we want to check if the value is not equal when a different object is given to be compared.
We can modify the test as follows at The Line:

----
    assertThat(theBiscuit, not(equalTo(myBiscuit))); // The Line
----

Thus, with Hamcrest, you can construct various conditions from (relatively) limited number of `Matcher` classes.
Now you can write a human-readable test which prints a human-readable failure report.

However, there are still two remaining pain points:

- To test your own class, you will need to implement a custom matcher class for better readability.
This is not a straight forward task.
- Hamcrest was designed and published at the age where Java 8 did not exist, which introduced lambda and `Predicate`.
Neither using a matcher as a predicate nor the other way around is not straight forward, although it will be convenient if it is possible.

The approach `pcond` took is as follows.

- Introduce the "Transform-and-check" concept to uniform the check.
This will allow us to support our own class just by writing a printable function to convert the object to already fixed types.
- Use Java's out-of-box `Predicate` and `Function` for that.

Following is the simplest example of `pcond` style test.

[source,java]
----
public class UTExample {
  @Test
  public void shouldPass_testFirstNameOf() {
    String firstName = NameUtils.firstNameOf("Yoshihiko Naito");
    assertThat(firstName, allOf(not(containsString(" ")), startsWith("Y")));
  }
}
----

`and`, `not`, `containsString`, and `startsWith` are just predicates of Java.
If you want to do a custom check, you can write your own predicate, as usual programming.
If you watn to check your custom class, you can write your own function, which converts your custom value to well-known types such as `String`, `Number`, `Boolean`, `List` of them, etc., as usual programming.
If the `NameUtils.firstNameOf` returns an empty string, it will print the following error message.

----
 org.junit.ComparisonFailure: Value:"" violated: (!containsString[" "]&&startsWith["R"])
  ""->&&                     ->true |""->&&                     ->false
        !                    ->true |      !                    ->true
          containsString[" "]->false|        containsString[" "]->false
 X      startsWith["Y"]      ->true |      startsWith["Y"]      ->false
----

For an equivalent test, what Hamcrest prints as an error report is:
----
java.lang.AssertionError:
Expected: (not a string containing " " and a string starting with "R")
     but: a string starting with "R" was ""
----

As you see, `pcond` gives more informative report.
It shows each predicate's expected actual predicate one by one and with a modern IDE, those will be shown side-by-side.
You will notice the only last predicate `startsWith["Y"]` was not satisfied by the value `""` and that's why the test failed.

While you will need to analyze which part of the `Expected` was not satisfied by the input value `""` and how by yourself from the Hamcrest's report.

=== Fluent Style (Experimental)

The next challenge assertion libraries faced was the explosion of the static methods to be imported.
There is a bunch of static methods to be imported and classes to which they belong.
Hamcrest itself has twenty-four matcher classes, each of for which entry point class is necessary.
On top of that, there is a bunch of third party libraries.

What the author of AssertJ or Google Truth thought is to let programmers create a builder object first by a static method and then from the object, let programmers choose the next method to call using "fluent" style.

Following is the example for the usage of AssertJ based testing code:

[source, java]
----
class AssertJExample {
  public void assertJexample() {
    // AsssertJ example from:
    // - https://assertj.github.io/doc/#overview-what-is-assertj
    // in the examples below fellowshipOfTheRing is a List<TolkienCharacter>
    assertThat(fellowshipOfTheRing).hasSize(9)
                                   .contains(frodo, sam)
                                   .doesNotContain(sauron);
  }
}
----

Major drawback of this approach is.:

- No clean way to verify multiple values.
- Still users need to write their own assertion builder class (`Assert` in AssertJ, `Subject` in Google Truth)
- Each builder class will need to have a number of methods.
This is because a builder just can "add" a simple check by one method.
No way to create a new one from existing ones.

Adding an explanation only to the first point as the other two are more or less obvious.
When you need to do assertions for multiple values in `AssertJ`, a normal way to achieve it is following:

[source, java]
----
public static class AssertJMultiValueExample {
  public void assertjMultiValueExample() {
    // https://stackoverflow.com/questions/47397525/multiply-conditions-set-in-assertj-assertions
    SoftAssertions phoneBundle = new SoftAssertions();
    phoneBundle.assertThat("a").as("Phone 1").isEqualTo("a");
    phoneBundle.assertThat("b").as("Service bundle").endsWith("c");
    phoneBundle.assertAll();
  }
}
----

This is a bit verbose, and it will silently PASS, if you forget calling `assertAll` in the end.

An example for the `pcond` 's fluent style support looks like the following:

[source,java]
----
public class MoreFluentExample {
  @Test
  public void checkTwoValues() {
    String s = "HI";
    List<String> strings = asList("HELLO", "WORLD");

    assertAll(
        valueOf(s).asString()
          .exercise(TestUtils.stringToLowerCase())
          .then()
          .isEqualTo("HI"),
        valueOf(strings).asListOf((String)value())
          .then()
          .findElementsInOrder("hello", "world"));
  }
}
----

This leads to the following report.:

----
  "HI"             ->WHEN:treatAsString        ->"HI"
                       stringToLowerCase       ->"hi"
 X"hi"             ->THEN:isEqualTo["HI"]      ->false
  ["HELLO","WORLD"]->WHEN:treatAsList          ->["HELLO","WORLD"]
                              :
                              :
  []               ->    (end)                 ->true
----

Thus, we can keep both the code and report human-readable.

== Related Works

- [[hamcrest, 2]] Hamcrest, Matchers that can be combined to create flexible expressions of intent https://hamcrest.org/[Hamcrest]: 2019
- [[hamcrest-tutorial, 3]] Hamcrest, Hamcrest Tutorial https://hamcrest.org/JavaHamcrest/tutorial[Hamcrest Tutorial]: 2019
- [[assertj, 4]] AssertJ, Fluent assertions for java https://joel-costigliola.github.io/assertj/[AssertJ]: 2022
- [[truth, 5]] Truth - Fluent assertions for Java and Android Truth https://truth.dev/[Truth]: 2022

Enjoy.